---
exclude_paths:
  - collectors/python.d.plugin/python_modules/pyyaml2/**
  - collectors/python.d.plugin/python_modules/pyyaml3/**
  - collectors/python.d.plugin/python_modules/urllib3/**
  - collectors/python.d.plugin/python_modules/lm_sensors.py
  - web/css/**
  - web/lib/**
  - web/old/**
  - collectors/node.d.plugin/node_modules/lib/**
  - collectors/node.d.plugin/node_modules/asn1-ber.js
  - collectors/node.d.plugin/node_modules/net-snmp.js
  - collectors/node.d.plugin/node_modules/pixl-xml.js
  - collectors/node.d.plugin/node_modules/extend.js
  - tests/**
