version: "2"
checks:
  argument-count:
    enabled: false
    config:
      threshold: 6
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: false
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: false
    config:
      threshold: 20
  method-lines:
    enabled: false
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
  identical-code:
    enabled: true
plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
          mass_threshold: 20
      - python:
          python_version: 3
          mass_threshold: 20
    checks:
      Similar code:
        enabled: false
      Identical code:
        enabled: false
  eslint:
    enabled: true
    checks:
      max-statements:
        enabled: false
      complexity:
        enabled: false
      no-eval:
        enabled: false
      no-extend-native:
        enabled: false
      no-void:
        enabled: false
      no-alert:
        enabled: false
      no-undef-init:
        enabled: false
  fixme:
    enabled: false
  phpmd:
    enabled: true
  radon:
    enabled: true
    checks:
      Complexity:
        enabled: false
exclude_patterns:
  - ".gitignore"
  - "conf.d/"
  - "hooks/"
  - "tests/"
  - "m4/"
  - "web/css/"
  - "web/lib/"
  - "web/fonts/"
  - "web/old/"
  - "python.d/python_modules/pyyaml2/"
  - "python.d/python_modules/pyyaml3/"
  - "python.d/python_modules/urllib3/"
  - "node.d/node_modules/lib/"
  - "node.d/node_modules/asn1-ber.js"
  - "node.d/node_modules/extend.js"
  - "node.d/node_modules/pixl-xml.js"
  - "node.d/node_modules/net-snmp.js"

