---
exclude_paths:
  - collectors/python.d.plugin/python_modules/pyyaml2/**
  - collectors/python.d.plugin/python_modules/pyyaml3/**
  - collectors/python.d.plugin/python_modules/urllib3/**
  - collectors/python.d.plugin/python_modules/third_party/**
  - web/css/**
  - web/lib/**
  - web/old/**
  - web/gui/src/**
  - collectors/node.d.plugin/node_modules/**
  - tests/**
