dist: trusty
sudo: true
#
# C includes autotools and make by default
language: c
services:
  - docker
os:
  - linux
  - osx
compiler:
 - gcc
 - clang
#
# Extra packages
addons:
  apt:
    packages:
    - gnupg
    - libcap2-bin
    - zlib1g-dev
    - uuid-dev
#
# Setup environment
before_install:
 - eval "$(ssh-agent -s)"
 - ./.travis/decrypt-if-have-key decb6f6387c4
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall gnupg || echo; brew install gpg; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install fakeroot; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ossp-uuid; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install xz; fi
#
# Run
before_script:
 - gpg --import packaging/gpg.keys
 # Run the commit hooks in case the developer didn't
 - git diff 4b825dc642cb6eb9a060e54bf8d69288fbee4904 | ./packaging/check-files -
script:
   # make release packages
 - fakeroot ./packaging/git-build
   # make self-extractor
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./makeself/build-x86_64-static.sh; fi
   # test build and installer
 - fakeroot ./netdata-installer.sh --install $HOME --dont-wait --dont-start-it
#
# Deploy as required
after_success:
  - for i in *.tar.*; do md5sum -b $i > $i.md5; sha512sum -b $i > $i.sha; done
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then for i in *.gz.run; do md5sum -b $i > $i.md5; sha512sum -b $i > $i.sha; done; fi
  - ./.travis/deploy-if-have-key
deploy:
  # Upload results to GitHub (tag only)
  - provider: releases
    draft: true
    api_key:
      secure: invJ0ZdNOPi9x8JJmFkqSIQMxljkLROwgRFCbmXMausJ0rA4E/PgLtM7ddWrHlu6lu8N9e5Pus4bG8DWATHbY0blMUhL5C82S5KK4mxAANLCLgTV8Qr7dMWnMqRV/OJBMGM1ZWpC2AA5GVhPLF7Z++54iqK+LM8P0EuOTAKbebIWCIkGybbSpXj+jJqaQXY0tLGSn5fXPFfyV3Tw0URJPcO3Uz5iukELngkLVSve2d0XYwy8M5tpLKHJi5bzc9CwcJZ/JK1WvklqmV3fNdSSzZunaAfDwWosV3hO7QcGnAVEbNl0HBKZJ8JkriV2fDbH4fttoSvLO2tW9HauP7Yf5XqLDudqUj4gPTuGzd31vRb9kx9cAulfE9onMAmDbjbne8Cp2Bq9/yBEqaofqEIaRcLgnlZSNc+PWbH4FQJ6fIOs5nfqLJo0G+3isgRWrqxp/rjILOvbIGbfLkbPl9aV09IvzShyW2lK7E+QOP0TZIwyXGT0NW0Rr/eyzuMXooy8wi9NehKfrxIcUr7784nU2E+EtItrhtTkJpK8XBBh16swn7s2sQ89qx9PYd/wE5qnKfG0yy3SSc2ycKzEpH7Cy3E6lC4Jytw0AM1Mc179WASBhlR2tyElkRcuhlqOFlJ/6iXjp3kqSgW4kvWbwHwT6VsyiDRhf+Ir4XILFBJ26Z8=
    skip_cleanup: true
    file_glob: true
    file:
      - "netdata*.tar.*"
      - "netdata*.gz.run*"
    on:
      condition: $CC = gcc && $TRAVIS_OS_NAME = linux
      repo: firehol/netdata
      tags: true
