language: c
compiler:
 - gcc
 - clang
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq automake make libcap2-bin zlib1g-dev uuid-dev
script:
   # default build
 - ./autogen.sh && ./configure && make -j4

   # test installer
 - fakeroot ./netdata-installer.sh --install $HOME --dont-wait --dont-start-it
