dist: trusty
sudo: true
language: c
services:
- docker

stages:
- test
- build
- name: packaging
  if: branch = master AND type != pull_request AND type != cron
- name: nightlies
  if: branch = master AND type = cron

jobs:
  include:
  - stage: test
    name: C
    install: sudo apt-get install -y libcap2-bin zlib1g-dev uuid-dev fakeroot libipmimonitoring-dev libmnl-dev libnetfilter-acct-dev
    script: fakeroot ./netdata-installer.sh --install $HOME --dont-wait --dont-start-it --enable-plugin-nfacct --enable-plugin-freeipmi --disable-lto && $HOME/netdata/usr/sbin/netdata -W unittest
    env: CFLAGS='-O1 -DNETDATA_INTERNAL_CHECKS=1 -DNETDATA_VERIFY_LOCKS=1'
  - name: dashboard.js
    script: cp web/gui/dashboard.js /tmp/dashboard.js && ./build/build.sh && diff /tmp/dashboard.js web/gui/dashboard.js
  - name: coverity
    install: sudo apt-get install -y zlib1g-dev uuid-dev libipmimonitoring-dev libmnl-dev libnetfilter-acct-dev
    script: ./coverity-scan.sh || echo "Coverity failed :("
    env: INSTALL_COVERITY="true"
    if: type = cron

  - stage: build
    name: OSX
    install: brew install fakeroot ossp-uuid
    script: fakeroot ./netdata-installer.sh --install $HOME --dont-wait --dont-start-it
    os: osx
  - name: ubuntu 14.04 (not containerized)
    install: sudo apt-get install -y libcap2-bin zlib1g-dev uuid-dev fakeroot
    script: fakeroot ./netdata-installer.sh --dont-wait --dont-start-it --install $HOME
  - name: alpine + lifecycle
    script: docker run -it -v "${PWD}:/code:rw" -w /code "netdata/os-test:alpine" ./tests/lifecycle.sh
  - name: ubuntu 18.04
    script: docker run -it -v "${PWD}:/code:rw" -w /code "netdata/os-test:ubuntu1804" ./netdata-installer.sh --dont-wait --dont-start-it --install /tmp
  - name: CentOS 7
    script: docker run -it -v "${PWD}:/code:rw" -w /code "netdata/os-test:centos7" ./netdata-installer.sh --dont-wait --dont-start-it --install /tmp
  - name: CentOS 6
    script: docker run -it -v "${PWD}:/code:rw" -w /code "netdata/os-test:centos6" ./netdata-installer.sh --dont-wait --dont-start-it --install /tmp

  - stage: packaging
    name: Create release
    install:
    - sudo apt-get install -y gnupg libcap2-bin zlib1g-dev uuid-dev fakeroot python-pip
    - sudo apt install -y --only-upgrade docker-ce
    - docker info
    before_script: sudo pip install git-semver
    script: ".travis/releaser.sh && .travis/labeler.sh" # labeler should be replaced with GitHub Actions when they hit GA
    git:
      depth: false

  - stage: nightlies
    name: docker images
    install:
    - sudo apt install -y --only-upgrade docker-ce
    - docker info
    script: "packaging/docker/build.sh"
    env: REPOSITORY="netdata/netdata"
  - name: tarball and self-extractor build
    install: sudo apt-get install -y gnupg libcap2-bin zlib1g-dev uuid-dev fakeroot
    script: ".travis/create_artifacts.sh"
    deploy:
      provider: gcs
      secret_access_key:
        secure: MWzWydVG2WJ+5S7bVQYHCcLTiC5s5l2yB3zb/E/HJUIjvv9AFZRsLmjS20umho+4MPK6dXJpI0IzWhW8V54cfFwyPHCeHGO+CBaREmWJJHQn53oiugLoFMlngSFzSAx9BGT1dfeJPxGQm1rqYk2ohLPfuKd1ORoEMK8fgnihmsn3GtNOhiJmmKyzppoottvihQBRhgy8aghkpd+3x1nKhQFeOcCvUwk6rWW4MBdRK3j6Nk3+Tlh/8s6p+FPwbIB63g9SPYBetBLvqp0ftleoUXY0Fy+tN4pR8CnhXHI4IJcesffa6JMxrQtx0CQJQrlxtRrDib0s+2zOw+wUlLfJcVMV+lyd6wvg4ltiQBYrNewA0ORmYYZVqd8ysZ8yXkQVNLkga15DNHV6uLlRkDny1xiT7buSHQc/xlT11ygOPfFJI4hMJbVSRyl+ChYsV5bJ0MBAOhH3AbBY//RZHWSed5oXugmlV6FKXcfbJOiAYPiVMjWpGVGqQexzQvbCfSNCERCTgKqAI3cFGXaiLOhvzkb0mdT4eOdvkzcWju6ucXiwnd1lNYN4ucKcazGjOL8vy5WfT0AKVlvBq7KtlQJ2vXJ1hJ2/ZOg8o88WyRBiiyMDxMBicSx6VNZhu2s2JFBPdaHxOoFcZjw9FLv04BA7GeUh0WGvasoSCA4mNIZz+PY=
      access_key_id:
        secure: K1zxe4IWfeguYEAYCcLaQ1SCJcFEQ34PR3ffDuUuP1+HLqpHmAXtZUF2dnOT+PPRGSIHiUYwQNwGKuYz9P9IlKT0e9szeHE2IEJ+S9sO3TXXdnjoxkPWtVomeWo7pVqeIvs892qQHoqbHeVMwktB1D3vVFFAsNLl6OxxbATWEb8irjJOAY3pvjz0ebFeObeofaM6TUknWtp5ePyxn73joYRpj9dYK7i3drciOoOOOok7QZsE2diGwrIPbMar66GB3gdS4/KBYXq0ZANrT/pTPfGXFg5zEvDeQfW11pihq6w5OfsSk4wIe3iHTowFpaLexgZM8fchbHmg2QJL7iX80HxReuPPFlAte7XLHuN9JhrwUs1u52WMNmTXlQoQFVLpSlVPDX/+qdFsLW/FUPBpVKh0k4t5fiDQVtOoPF7MpR1lt4jp6gt0toA+qSRtuOK1Tqanxez/G8vWtSkpcWZbwOG46oCCp+ymrkK9dvAuCL0L8ruAaLmyYdC3S3Ho6e5Oh+m7Dr+yho83olk9S8XhaWYenCj80yCbs37IoekEw5axSIblfdGrQkahWynT+uOHAzRmruwE2C+NIUm27hROiSmNkLdKF/v4mc3pvHVBqrthcjlpts536kkty2tsxcR9hx28SwST28MvLPavdTWqphHf0S+/pAnO9nQA/e/VzWI=
      bucket: "netdata-nightlies"
      skip_cleanup: true
      file_glob: true
      file: "netdata*.tar.gz"
  - name: changelog generation
    script: ".travis/generate_changelog.sh"
    env: COMMIT_AND_PUSH=1
    git:
      depth: false

notifications:
  webhooks: https://app.fossa.io/hooks/travisci
  slack:
    rooms:
      - secure: "NuW1p7s+WGLcyhEceeiLRSV1JgAc6N47zgdSsYoxrjSFRQHDfc8jensypDcEJwgs1K2Hcve9iKRaAddEHEw7AkS6rie9gFR5HmmbKXfW2GFMqOr6maYTFsvaECPqiWk1n9/XnRLsAi5kZ8HxH+a8ldb/eaVoFQesY1jPXgh11BM5DwvpXjEtwg0WGASsKiymvnXFS3KcC+sR7Lln2GX1a8vfCX2I3TEmOedKMlSHUy5JilGGC3AWA0SWS8tR8PUH0u3dHL5j0RNIr1RO3Yx24QgUpg/YpvKymnW/iIIEOq2vb2mBhhiKEQjJ1djUL4VSPzjIDpUzThVpKaHk3syOp6W9qZEHKhR/sqjc5Yk2XRjsw1cM0nS60gaCgxtKhEMKWcjtvWf04oJAVrmcUwcYXj0eA+jgRCZl5VhyufK/fUJavjOfsQGjwhdjxQfwDCw33W17ypJUt4GZngdb6jbIhEOcKHSLQDu1vuHTw82hJJkthkmR59PX30qJdl/MEGcfVLdN/fkCokjR/qwfmkNwQm+wYSKsK/Jq4RgBT0/oZwY3e8nkCq2ov7lBbDO3/0rzQKWZ9Uy//tnoCM3vGhDwGHQxsHshv7g6KwdhYTcmm7WWWIucfLupcjFUO1HbRuJ+7ZnvxRRwKiV+MGkFT2SNJkS8q1/jCu9KGbmktd0WUSE="
