dist: trusty
sudo: true
#
# C includes autotools and make by default
language: c
services:
  - docker
os:
  - linux
  - osx
compiler:
 - gcc
 - clang
#
# Extra packages
addons:
  apt:
    packages:
    - gnupg
    - libcap2-bin
    - zlib1g-dev
    - uuid-dev
    - fakeroot
#
# Setup environment
before_install:
 - eval "$(ssh-agent -s)"
 - ./.travis/decrypt-if-have-key decb6f6387c4
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew uninstall gnupg || echo; brew install gpg; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install fakeroot; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install ossp-uuid; fi
 - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install xz; fi
#
# Run
before_script:
 - gpg --import packaging/gpg.keys
 # Run the commit hooks in case the developer didn't
 - git diff 4b825dc642cb6eb9a060e54bf8d69288fbee4904 | ./packaging/check-files -
script:
   # make release packages
 - fakeroot ./packaging/git-build
   # Make sure stdout is in blocking mode. If we don't, then conda create will barf during downloads.
   # See https://github.com/travis-ci/travis-ci/issues/4704#issuecomment-348435959 for details.
 - python -c 'import os,sys,fcntl; flags = fcntl.fcntl(sys.stdout, fcntl.F_GETFL); fcntl.fcntl(sys.stdout, fcntl.F_SETFL, flags&~os.O_NONBLOCK);'
   # make self-extractor
 - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./makeself/build-x86_64-static.sh; fi
   # test build and installer
 - fakeroot ./netdata-installer.sh --install $HOME --dont-wait --dont-start-it
#
# Deploy as required
after_success:
  - for i in *.tar.*; do md5sum -b $i > $i.md5; sha512sum -b $i > $i.sha; done
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then for i in *.gz.run; do md5sum -b $i > $i.md5; sha512sum -b $i > $i.sha; done; fi
  - ./.travis/deploy-if-have-key
deploy:
  # Upload results to GitHub (tag only)
  - provider: releases
    draft: true
    api_key:
      secure: hbyuWsTshQ8Ixrgla2J6xtBNhQ1OjjaQ7hUEteclHrlx6i8B1ughCdhC3bYE1VGKClmq9mUvuZxcPGDDUaMBoLYTNaFx93IWorlrB29mpeNPd3b+DZqOePBYqU6NCA7PQccEUBkXJrGS44ZNg+pHFVCHMBe99+5u1Dfx/IJW0ojOb9XOfde6p5aL7syYWYXR/Ov/K40QAgpEDhAKUY4T1D/Yyk2ucdh6QsM00aq51F3D1SxIcFXcnBpacD3iGdkd3fM+c9PLMtq47mOicRjJsDnXYV58/upzmR9OPJYBbOPtNy0UKRl3f81cm5O4X3wcUBUMV4AQew8udy06TlWu2SQipGeh0RPDspRrBIqKhPJGX+h4Zyw/9iGvsDPetQqgoAsPqcruKGqNjC538LXr/fi8mur35VcKhmxi6gH7SNbs7TXfVLnrvNGgr6KCcKoLvFMxsJW1fQObVOq2mO+MwH6wQbqfRIo8btu6WVrzI4cYkZomny2i4D5YWVfTYEJ+BSTZCZ/l/RvxEYPUPFGyASxZ1OVCYA2in1JYdiPPMwK4gH66nYJG+ZDeTK5JUlXZAELZSRcDzecOAbi5zS/C3XXiGaHOXZBXjI0Gsw4kDaZn0xGUIzBFvMoSf1SMw5CuJ1kbSIzi4VGU1v85JaCB4znQ4pA4Yvw0/5l/q/B08aI=
    skip_cleanup: true
    file_glob: true
    file:
      - "netdata*.tar.*"
      - "netdata*.gz.run*"
    on:
      condition: $CC = gcc && $TRAVIS_OS_NAME = linux
      repo: firehol/netdata
      tags: true
