---
dist: trusty
sudo: true

# C includes autotools and make by default
language: c
services:
  - docker

stages:
  - lint
  - test
  - build
  - name: release
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: "lint"
      name: "python"
      install: skip
      script: docker run --rm -v $(pwd):/code eeacms/pylint || echo "OK"
    - name: "javascript"
      install: skip
      script: docker run -it --rm -v $(pwd)/web:/code eeacms/jslint --color /code/web/*.js /code/plugins.d/node.d.plugin/*.js /code/node.d/*.js /code/node.d/node_modules/netdata.js
    - name: "css"
      install: skip
      script: docker run --rm -v $(pwd)/web:/code eeacms/csslint sh -c "csslint /code/*.css" || echo "OK"
    - name: "bash"
      install: skip
      script: docker run --rm --volume "$(pwd)":/project:ro --entrypoint sh koalaman/shellcheck-alpine:v0.4.7 -c 'for file in $(find /project/ -type f -name "*.sh"); do if ! shellcheck --format=gcc $file; then export FAILED=true; fi; done; if [ "$FAILED" != "" ]; then exit 1; fi' || echo "OK"
    - stage: "test"
      name: "C"
      install: sudo apt-get install -y libcap2-bin zlib1g-dev uuid-dev fakeroot libipmimonitoring-dev libmnl-dev libnetfilter-acct-dev
      script: fakeroot ./netdata-installer.sh --install $HOME --dont-wait --dont-start-it --enable-plugin-nfacct --enable-plugin-freeipmi --disable-lto && $HOME/netdata/usr/sbin/netdata -W unittest
      env: CFLAGS='-O1 -DNETDATA_INTERNAL_CHECKS=1 -DNETDATA_VERIFY_LOCKS=1'
#      env: CFLAGS='-O1 -ggdb -Wall -Wextra -Wformat-signedness -fstack-protector-all -DNETDATA_INTERNAL_CHECKS=1 -D_FORTIFY_SOURCE=2 -DNETDATA_VERIFY_LOCKS=1'
#    - name: "Node.js"
#      script: tests/run_nodejs.sh
    - stage: "build"
      name: "linux"
      install: sudo apt-get install -y libcap2-bin zlib1g-dev uuid-dev fakeroot
      script: fakeroot ./netdata-installer.sh --install $HOME --dont-wait --dont-start-it
    - name: "OSX"
      install: brew install fakeroot ossp-uuid
      script: 
        - fakeroot ./netdata-installer.sh --install $HOME --dont-wait --dont-start-it
      os: osx
    - stage: "release"
      name: "Docker"
      script: docker/build.sh
      env: REPOSITORY="firehol/netdata"
    - name: "GitHub"
      install: sudo apt-get install -y gnupg libcap2-bin zlib1g-dev uuid-dev fakeroot
      script: ./.travis/create_artifacts.sh
      deploy:
        - provider: releases
          draft: true
          api_key:
            secure: hbyuWsTshQ8Ixrgla2J6xtBNhQ1OjjaQ7hUEteclHrlx6i8B1ughCdhC3bYE1VGKClmq9mUvuZxcPGDDUaMBoLYTNaFx93IWorlrB29mpeNPd3b+DZqOePBYqU6NCA7PQccEUBkXJrGS44ZNg+pHFVCHMBe99+5u1Dfx/IJW0ojOb9XOfde6p5aL7syYWYXR/Ov/K40QAgpEDhAKUY4T1D/Yyk2ucdh6QsM00aq51F3D1SxIcFXcnBpacD3iGdkd3fM+c9PLMtq47mOicRjJsDnXYV58/upzmR9OPJYBbOPtNy0UKRl3f81cm5O4X3wcUBUMV4AQew8udy06TlWu2SQipGeh0RPDspRrBIqKhPJGX+h4Zyw/9iGvsDPetQqgoAsPqcruKGqNjC538LXr/fi8mur35VcKhmxi6gH7SNbs7TXfVLnrvNGgr6KCcKoLvFMxsJW1fQObVOq2mO+MwH6wQbqfRIo8btu6WVrzI4cYkZomny2i4D5YWVfTYEJ+BSTZCZ/l/RvxEYPUPFGyASxZ1OVCYA2in1JYdiPPMwK4gH66nYJG+ZDeTK5JUlXZAELZSRcDzecOAbi5zS/C3XXiGaHOXZBXjI0Gsw4kDaZn0xGUIzBFvMoSf1SMw5CuJ1kbSIzi4VGU1v85JaCB4znQ4pA4Yvw0/5l/q/B08aI=
          skip_cleanup: true
          file_glob: true
          file:
            - "netdata*.tar.*"
            - "netdata*.gz.run*"
          on:
            repo: firehol/netdata
            tags: true

notifications:
  webhooks: https://app.fossa.io/hooks/travisci
