version: '3.3'
services:
  agent_master:
    image: debian_10_dev
    command: /usr/sbin/netdata -D
    ports:
    - 21000:19999
    volumes:
    - ./master_stream.conf:/etc/netdata/stream.conf:ro
    - ./master_guid:/var/lib/netdata/registry/netdata.public.unique.id:ro
    - ./min.conf:/etc/netdata/netdata.conf:ro
    cap_add:
    - SYS_PTRACE
