version: '3.3'
services:
  agent_slave:
    image: debian_10_dev
    command: /usr/sbin/netdata -D
    #ports:
    #- 21002+:19999
    volumes:
      - ./slave_stream.conf:/etc/netdata/stream.conf:ro
      #- ./slave_guid:/var/lib/netdata/registry/netdata.public.unique.id:ro
      - ./min.conf:/etc/netdata/netdata.conf:ro
    cap_add:
    - SYS_PTRACE

