---
name: Docker
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/docker.yml'
      - 'netdata-installer.sh'
      - 'packaging/**'
  pull_request:
    paths:
      - '.github/workflows/docker.yml'
      - 'netdata-installer.sh'
      - 'packaging/**'
  workflow_dispatch:
    inputs:
      version:
        name: Version Tag
        default: latest
        required: true
jobs:
  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Determine if we should push changes and which tags to use
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.version != 'nightly'
        run: |
          echo "publish=true" >> $GITHUB_ENV
          echo "tags=netdata/netdata:latest,netdata/netdata:stable,netdata/netdata:${{ github.event.inputs.version }}" >> $GITHUB_ENV
      - name: Determine if we should push changes and which tags to use
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.version == 'nightly'
        run: |
          echo "publish=true" >> $GITHUB_ENV
          echo "tags=netdata/netdata:latest,netdata/netdata:edge" >> $GITHUB_ENV
      - name: Determine if we should push changes and which tags to use
        if: github.event_name != 'workflow_dispatch'
        run: |
          echo "publish=false" >> $GITHUB_ENV
          echo "tags=netdata/netdata:test" >> $GITHUB_ENV
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1
      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker Hub Login
        if: github.event_name == 'workflow_dispatch'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Docker Build
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/i386,linux/arm/v7,linux/arm64
          push: ${{ env.publish }}
          tags: ${{ env.tags }}
