---
name: Docker
on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/docker.yml'
      - 'netdata-installer.sh'
      - 'packaging/**'
  pull_request:
    paths:
      - '.github/workflows/docker.yml'
      - 'netdata-installer.sh'
      - 'packaging/**'
jobs:
  docker-build:
    name: 'Build'
    strategy:
      matrix:
        arch:
          - 'amd64'
          - 'i386'
          - 'arm'
          - 'arm64'
        include:
          - arch: 'arm'
            pre: 'docker run --rm --privileged multiarch/qemu-user-static --reset -p yes > /dev/null'
          - arch: 'arm64'
            pre: 'docker run --rm --privileged multiarch/qemu-user-static --reset -p yes > /dev/null'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test Docker Build for ${{ matrix.arch }}
        env:
          PRE: ${{ matrix.pre }}
        run:
          docker build . --no-cache --build-arg ARCH=${{ matrix.arch }} --file Dockerfile
