---
# Handles labelling of PR's.
name: Pull Request Labeler
on:
  pull_request:
    types:
      - opened
      - synchronized
      - reopened
      - ready_for_review
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
